### PR TITLE
Support JSON serialization with System.Text.Json

### LINKED ISSUE #2495: Support JSON serialization with System.Text.Json
### Is your feature request related to a problem? Please describe.

Stripe.NET takes a hard dependency on the Netwonsoft.Json serializer which is fine for some cases. Starting with [ASP.NET Core 3.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-3.0?view=aspnetcore-6.0#new-json-serialization), the default JSON serializer has changed to System.Text.JSON. 

For ASP.NET Core applications running on v3.0+ that use our Stripe.NET nuget package, developers have to be concerned with the inconsistencies between the serializers when working with Stripe Objects like Products, Customers, etc. 

Serialized single Stripe Product w/ Newtonsoft
```json
{
  "object": "product",
  "active": true,
  "attributes": [],
  "caption": null,
  "created": 1650997792,
  "deactivate_on": null,
  "default_price": null,
  "description": "This is such an awesome product made out of Metal",
  "images": [
    "https://picsum.photos/640/480/?image=279"
  ],
  "livemode": false,
  "metadata": {
    "code": "XXFYF3V"
  },
  "name": "Gorgeous Plastic Pants",
  "package_dimensions": null,
  "shippable": true,
  "statement_descriptor": null,
  "tax_code": null,
  "type": "service",
  "unit_label": null,
  "updated": 1650997792,
  "url": null
}
```

Serialized single Stripe Product w/ System.Text.Json
```json
{
  "Object": "product",
  "Active": true,
  "Attributes": [],
  "Caption": null,
  "Created": "2022-04-26T18:29:52Z",
  "DeactivateOn": null,
  "DefaultPriceId": null,
  "DefaultPrice": null,
  "Deleted": null,
  "Description": "This is such an awesome product made out of Metal",
  "Images": [
    "https://picsum.photos/640/480/?image=279"
  ],
  "Livemode": false,
  "Metadata": {
    "code": "XXFYF3V"
  },
  "Name": "Gorgeous Plastic Pants",
  "PackageDimensions": null,
  "Shippable": true,
  "StatementDescriptor": null,
  "TaxCodeId": null,
  "TaxCode": null,
  "Type": "service",
  "UnitLabel": null,
  "Updated": "2022-04-26T18:29:52Z",
  "Url": null,
  "RawJObject": null,
  "StripeResponse": null
}
```

You'll notice that the expected casing is different as well as the number of returned properties. Below are examples of serializing a StripeList<Product>

Serialized StripeList of Product w/ Newtonsoft.Json
```json
{
  "object": "list",
  "data": [
    {
      "id": "prod_La3FD0M3LXeUPE",
      "object": "product",
      "active": true,
      "attributes": [],
      "caption": null,
      "created": 1650997792,
      "deactivate_on": null,
      "default_price": null,
      "description": "This is such an awesome product made out of Metal",
      "images": [
        "https://picsum.photos/640/480/?image=279"
      ],
      "livemode": false,
      "metadata": {
        "code": "XXFYF3V"
      },
      "name": "Gorgeous Plastic Pants",
      "package_dimensions": null,
      "shippable": true,
      "statement_descriptor": null,
...
  ],
  "has_more": true,
  "url": "/v1/products"
}
```

Serialized StripeList of Product w/ System.text.json
```json
[
  {
    "Id": "prod_La3FD0M3LXeUPE",
    "Object": "product",
    "Active": true,
    "Attributes": [],
    "Caption": null,
    "Created": "2022-04-26T18:29:52Z",
    "DeactivateOn": null,
    "DefaultPriceId": null,
    "DefaultPrice": null,
    "Deleted": null,
    "Description": "This is such an awesome product made out of Metal",
    "Images": [
      "https://picsum.photos/640/480/?image=279"
    ],
    "Livemode": false,
    "Metadata": {
      "code": "XXFYF3V"
    },
    "Name": "Gorgeous Plastic Pants",
    "PackageDimensions": null,
    "Shippable": true,
    "StatementDescriptor": null,
...
    "RawJObject": null,
    "StripeResponse": null
  }
]
```

With lists you can see the data nesting between the serializers are also different.

### Describe the solution you'd like

Since System.Text.JSON is the default serializer for asp.net core web applications, It would be great if there could be some consistency with the expected responses when serializing/deserializing Stripe.NET object.

Can we have Stripe.NET use System.Text.JSON if available and fallback to Newtonsoft.JSON? Otherwise, I've seen other package authors create separate packages for each serializer but I'm not sure if we'd want to do that here.

### Describe alternatives you've considered

This can be mitigated by using the setting Newtonsoft.Json as the default serializer by using the [Microsoft.AspNetCore.Mvc.NewtonsoftJson](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.NewtonsoftJson) package.

Another option would be to return a custom response type instead of the plain Stripe object. For example, [see here](https://github.com/cecilphillip-stripe/stripe-checkout-events-sample/blob/05997d55f8b8d872840aa79a8a7dc087e2187ea9/src/StripeEventsCheckout.ApiServer/Controllers/EventsControllers.cs#L33-L42).

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hootanht**
Fixes #2495

Add support for JSON serialization with System.Text.Json.

* Add `JsonSerializer` interface and implement `NewtonsoftJsonSerializer` and `SystemTextJsonSerializer` classes in `src/Stripe.net/Infrastructure/JsonSerializer.cs`.
* Update `StripeEntity` class in `src/Stripe.net/Entities/_base/StripeEntity.cs` to use the `JsonSerializer` interface for `ToJson` and `FromJson` methods.
* Replace `Newtonsoft.Json` attributes with `System.Text.Json` attributes in `src/Stripe.net/Entities/Customers/Customer.cs`, `src/Stripe.net/Entities/_common/Address.cs`, `src/Stripe.net/Entities/_common/AddressJapan.cs`, `src/Stripe.net/Entities/_common/Shipping.cs`, `src/Stripe.net/Entities/AccountLinks/AccountLink.cs`, and `src/Stripe.net/Entities/Accounts/Account.cs`.
* Add conditional compilation to use appropriate attributes based on the selected JSON serializer in the above files.

### CODE REVIEW

**Comment by jar-stripe** [comment]
@hootanht Thank you submitting this PR!  Supporting System.Text.Json as an alternative to Newtonsoft is on our to-do list for this quarter, and I'd love to work with you on getting this landed.  We have a code generator that is responsible for generating some 500-odd files that I definitely don't want to ask you to manually update, and I want to be able to include this in such a way that one SDK will be compatible with users of both Newtonsoft and System.Text.Json.  Let me review your changes and see how we can incorporate them into our code generation infrastructure, make sure it won't break existing users, and then I'll plan to push updates right back to this branch/PR.  Sound good?

**Comment by hootanht** [comment]
> @hootanht Thank you submitting this PR!  Supporting System.Text.Json as an alternative to Newtonsoft is on our to-do list for this quarter, and I'd love to work with you on getting this landed.  We have a code generator that is responsible for generating some 500-odd files that I definitely don't want to ask you to manually update, and I want to be able to include this in such a way that one SDK will be compatible with users of both Newtonsoft and System.Text.Json.  Let me review your changes and see how we can incorporate them into our code generation infrastructure, make sure it won't break existing users, and then I'll plan to push updates right back to this branch/PR.  Sound good?

Awesome 👌

**Comment by jar-stripe** [comment]
Hi @hootanht !  Just a quick update here; I'm actually considering a more pared down approach here, to reduce the blast zone of a change while still solving the original ticket.  I left a comment over on the issue: https://github.com/stripe/stripe-dotnet/issues/2495#issuecomment-2468667732, mind giving it a read and chiming in there?  Thanks!

**Comment by hootanht** [comment]
Thanks a lot

**Comment by jar-stripe** [comment]
Sure thing!  And if that doesn't completely work for your use case we can definitely revisit this here.  Thanks again!

**Pull request closed without merging**
