### PR TITLE
Make it possible to expand Product on Plan

### PR DESCRIPTION
**Pull request by jmosbech**
This makes it much easier to work with the plans.

### CODE REVIEW

**Comment by jmosbech** [comment]
Hmm...

> Apple's domain verification service appears to be temporarily down. Please retry your request in a few minutes. We've been notified of the issue, but if this error persists, please feel free to contact us at support@stripe.com.

If this is a temporary problem, how should I move forward from here?

**Comment by remi-stripe** [comment]
@jmosbech I wouldn't worry about it, we can review the code and then re-run the tests if needed. Thanks a lot for your contribution!

**Comment by jmosbech** [comment]
You're welcome! Please let me know if something needs fixing.

**Comment by remi-stripe** [comment]
this LGTM but to be safe

r? @ob-stripe

**Comment by ob-stripe** [comment]
LGTM as well, but re-running the test suite for safety.

**Comment by ob-stripe** [comment]
Released as v13.0.1. Thanks for the contribution @jmosbech, much appreciated!

**Pull request merged**
