### PR TITLE
Add net60 and netcoreapp3.1 targets

### PR DESCRIPTION
**Pull request by jon-armen**
See #2410

### CODE REVIEW

**Comment by k3davis** [comment]
I hope this can be merged soon! Appears to be just a missing framework install on your CI platform...?

**Comment by jon-armen** [comment]
> I hope this can be merged soon! Appears to be just a missing framework install on your CI platform...?

I didn't have a chance to follow up on the CI side, I had just gotten the code running locally.  Thanks for pointing out, I'll see if the repo has the related files that would need to be updated to get that part working.

**Review by jchen293 — APPROVED** [review]

**Comment by jon-armen** [comment]
@jchen293 , what would the timeline be for this being merged in?

**Comment by k3davis** [comment]
Pretty please merge this... :)

**Comment by jon-armen** [comment]
@remi-stripe , @richardm-stripe , what would be the timeline for this to be merged?

**Comment by jon-armen** [comment]
r-codeowners?

**Comment by richardm-stripe** [comment]
Hello, thank you for the contribution @jon-armen. Very sorry for the delay on this, it has been released in [v39.90.0](https://github.com/stripe/stripe-dotnet/releases/tag/v39.90.0).

**Pull request merged**
