### PR TITLE
Changed single-use to single_use

### PR DESCRIPTION
**Pull request by Kaegun**
Looks like there's a typo in the Constants for Usage.

### CODE REVIEW

**Comment by remi-stripe** [comment]
@anelder-stripe assigning this one to you, looks like this one should be merged in though I'm surprised we didn't have test errors before this fix.

**Comment by remi-stripe** [comment]
r? @brandur-stripe @fred-stripe 
Bumping this one to make sure it gets handled soon

**Comment by remi-stripe** [comment]
@Kaegun Sorry for the delays on this one. We ship a lot of fixes today to the library. Would you mind rebasing your branch so that we can get it other the finish line?

Can you also add a test so that it confirms the change does work as expected?

**Comment by remi-stripe** [comment]
Closing this one as @ob-stripe pushed a new one in https://github.com/stripe/stripe-dotnet/pull/1084

**Comment by Kaegun** [comment]
Thank remi, can I delete the branch?

**Comment by remi-stripe** [comment]
@Kaegun you can as it's been fixed and merged already!

**Comment by Kaegun** [comment]
Done. Thanks for fixing it! :-)

**Pull request closed without merging**
