### PR TITLE
API Updates

### PR DESCRIPTION
**Pull request by pakrym-stripe**
Codegen for openapi 2956fca.
r? @dcr-stripe
cc @stripe/api-libraries

## Changelog
* Add support for Search API
   * Add support for `Search` method on resources `Charge`, `Customer`, `Invoice`, `PaymentIntent`, `Price`, `Product`, and `Subscription`

### CODE REVIEW

**Comment by pakrym-stripe** [comment]
PTAL @dcr-stripe ?

**Comment by pakrym-stripe** [comment]
Wait! Don't look, I forgot the integration test.

**Comment by pakrym-stripe** [comment]
Added the test. 
PTAL @dcr-stripe ?

**Review by dcr-stripe — APPROVED** [review]
LGTM! Thanks Pavel!

**Pull request merged**
