### PR TITLE
Release changes to the Payment Intent APIs before release

### PR DESCRIPTION
**Pull request by remi-stripe**
cc @stripe/api-libraries @danwang-stripe 
r? @ob-stripe

### CODE REVIEW

**Comment by ob-stripe** [comment]
I was referring to the spec itself, not the fixtures. The current spec doesn't list `on_behalf_of` as an attribute on `payment_intent`, and still has `return_url`.

**Comment by remi-stripe** [comment]
gotcha. Yeah unfortunately all of this is happening quite in parallel

**Comment by danwang** [comment]
@ob-stripe This is fixed as of https://github.com/stripe/openapi/commit/b9ff093112c091811b1cf452c281a778100daebb !

**Comment by remi-stripe** [comment]
We would need to wait for https://github.com/stripe/stripe-mock/pull/124 to be merged and released before we can integrate it. Thanks for doing that work @danwang

**Pull request merged**
