### PR TITLE
Cross target netstandard2.0

### PR DESCRIPTION
**Pull request by iamcarbon**
This PR adds netstandard2.0 to the target frameworks. This simplifies the dependency tree on modern runtimes.

### CODE REVIEW

**Comment by ob-stripe** [comment]
Hi @iamcarbon, thanks for the contribution!

Can you clarify how this helps exactly? I'd've thought that libraries would only need to target the _minimum_ version of .NET Standard that they require. Is that not the case?

**Comment by iamcarbon** [comment]
Hey there. Targeting NETSTANDARD2.0 directly eliminates the 50+ dependencies that come from .NETSTANDARD 1.x libraries. .NETSTANDARD2.0 reduces this to a single dependency (netstsandard.dll) that is already included in modern runtimes (netfx472, netcoreapp2.0, etc).

The official guidance from MSFT is now to re-baseline at 2.0x or multi-target:
https://twitter.com/davidfowl/status/1008453902058917888

**Comment by ob-stripe** [comment]
Cool, thanks @iamcarbon. Going to pull this in.

**Comment by ob-stripe** [comment]
Released as 19.9.2.

**Comment by ob-stripe** [comment]
Just for future reference in case someone stumbles upon this: https://github.com/dotnet/standard/blob/master/docs/versions.md#how-do-i-know-which-net-standard-version-i-should-target

> * You should target the lowest version you can get away with.
> * If you target .NET Standard 1.x, add .NET Standard 2.0 as [another target](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-target-frameworks).

**Pull request merged**
