### PR TITLE
Modify SessionCustomTextOptions to align with checkout api

### PR DESCRIPTION
**Pull request by tylergsb**
Bring New Checkout Session Custom Text to be compatible with Stripe API Version 2022-11-15

This fixes the src/Stripe.net/Services/Checkout/Sessions/SessionCustomTextOptions.cs model, in which it currently has type AddressOptions for SessionCustomTextOptions.ShippingAddress, which does not align with stripe API definitions.  This throws API exceptions when used.

SessionCustomTextOptions.ShippingAddress should be an object with a single "message" property.

See [https://stripe.com/docs/api/checkout/sessions/create](https://stripe.com/docs/api/checkout/sessions/create) for details on parameters expected for this.

### CODE REVIEW

**Review by anniel-stripe — CHANGES_REQUESTED** [review]
Hi, thanks so much for noticing and submitting this patch! However, I believe you meant to set the target base branch to 'master', not 'beta'.

**Comment by tylergsb** [comment]
> 

Hey thanks, I wasn't sure where to point PRs to. I adjusted it to master.  Let me know if there's anything else you need, and thanks for reviewing!

**Review by anniel-stripe — CHANGES_REQUESTED** [review]
Ah sorry I should have clarified, can you revert your merge with `beta` too (https://github.com/stripe/stripe-dotnet/pull/2644/commits/3d8eedbe934f4574e0ef10f44053fb183fd721e7)? We don't want to merge those changes into `master`.

It may be easier to open a new PR, or wait until tomorrow's release where we plan to address this.

**Comment by anniel-stripe** [comment]
As an update, this was fixed in [v41.7.0](https://github.com/stripe/stripe-dotnet/releases/tag/v41.7.0) after we updated our generator (we discovered this issue also existed in `PaymentLinkCustomTextOptions`). I'll be closing this PR, but thanks so much again for pointing out this issue!

**Pull request closed without merging**
