### PR TITLE
Exposing the StripeTypeRegistry.ObjectsToTypes publicly

### PR DESCRIPTION
**Pull request by clement911**
We are building some highly generic stripe components internally that will need a mapping from object to type.
Rather than maintaining our own, we'd prefer to leverage the one already existing in the library.
I wrapped the dictionary in a read only dictionary so that it can't be modified by consumers.

### CODE REVIEW

**Comment by clement911** [comment]
Sure it makes sense.
All done.

**Comment by ob-stripe** [comment]
Thanks! We'll merge and release this soon.

**Comment by ob-stripe** [comment]
Released as 34.6.0.

**Comment by clement911** [comment]
Thank you this is very useful!

**Pull request merged**
