### PR TITLE
Added ability to set tax on upcoming invoice request

### PR DESCRIPTION
**Pull request by bcrobinson**
The stripe api has the ability to set a tax rate on the upcoming invoice request
https://stripe.com/docs/api#upcoming_invoice-subscription_tax_percent

This pull request adds this property to the StripeUpcomingInvoiceOptions class.

### CODE REVIEW

**Comment by bcrobinson** [comment]
This is for issue https://github.com/stripe/stripe-dotnet/issues/1179

**Comment by remi-stripe** [comment]
@bcrobinson Thank you so much for taking the time to submit a PR and adding a test on top of this.

I can see that another parameter is not supported yet (it was added recently). Would you mind also adding support for it: [subscription_trial_from_plan](https://stripe.com/docs/api/dotnet#upcoming_invoice-subscription_trial_from_plan). You don't need a test for that one since it's just a boolean.

**Comment by remi-stripe** [comment]
Thank you so much for the quick work @bcrobinson 

r? @brandur-stripe 
cc @stripe/api-libraries

**Comment by brandur-stripe** [comment]
LGTM. Thanks @bcrobinson @remi-stripe.

**Comment by brandur-stripe** [comment]
Released as 16.1.0.

**Comment by bcrobinson** [comment]
No problem. Do you have an ETA on when the next version of the nuget package will be released, or if there's a nightly package we can use?

**Comment by brandur-stripe** [comment]
@bcrobinson Just as a quick follow up: there's a bit of a delay on the packages because they're pushed by our CI, so the build has to complete before they're available. That said, they're generally available within 30 minutes or so of when I announce one here.

**Pull request merged**
