### PR TITLE
stripe-dotnet v20.0

### LINKED ISSUE #1164: Add a custom plugin encoder for all DateTime parameters
Timestamps in the API are represented as DateTime in stripe-dotnet. Those have to be converted to a timestamp internally such as [here](https://github.com/stripe/stripe-dotnet/pull/1163) which is easy to forget.

It would be better to add a custom plugin encoder for those parameters as we do for other types [here](https://github.com/stripe/stripe-dotnet/tree/master/src/Stripe.net/Infrastructure/Middleware/ParserPlugin).

### LINKED ISSUE #1260: Extract sync/async interfaces from Stripe services
It would be nice if we could use stripe services in unit tests. I'm happy using stripe-mock in integration tests, but the way things are currently mean I'll have to abstract the stripe services if I want to unit test them.

In the project I'm working on it is mandatory that we test as much as is possible.

### LINKED ISSUE #1281: typo in stripeEvent for
there is a typo for the event "source.transaction.created", its named SourceTransactionCanceled in
https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Constants/StripeEvents.cs#L455

### LINKED ISSUE #1330: JsonReaderException: JSON integer is too large or small for an Int32. Path 'account_balance'
We use \packages\Stripe.net.11.9.0\lib\net45\Stripe.net.dll, nuget, version=11.9.0.0, IIS, Windows.

Call stack:
Newtonsoft.Json.JsonTextReader in ParseNumber at line 553:0
Void ParseNumber(Newtonsoft.Json.ReadType)
Newtonsoft.Json.JsonTextReader in ReadNumberValue at line 522:0
Newtonsoft.Json.JsonTextReader in ReadAsInt32
Newtonsoft.Json.Serialization.JsonSerializerInternalReader in ReadForType at line 74:0
Newtonsoft.Json.Serialization.JsonSerializerInternalReader in PopulateObject at line 615:0
Newtonsoft.Json.Serialization.JsonSerializerInternalReader in CreateObject at line 353:0
Newtonsoft.Json.Serialization.JsonSerializerInternalReader in Deserialize at line 217:0
Newtonsoft.Json.JsonSerializer in DeserializeInternal at line 69:0
Newtonsoft.Json.JsonConvert in DeserializeObject at line 44:0
Newtonsoft.Json.JsonConvert in DeserializeObject
Stripe.Mapper`1 in MapFromJson at line 27:0
Stripe.StripeCustomerService in Get

account
We can change account balance and set value more than is used in
https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/StripeCustomer.cs
for AccountBalance property.
So, please, add validation or change int to other type.

Thanks.

### LINKED ISSUE #1344: StripeEvents.ChargeExpired constant missing
Pretty easy one.  See the title.

### PR DESCRIPTION
**Pull request by ob-stripe**
This PR will be used for ongoing work on the library to merge multiple PRs introducing large breaking changes to the library

Done:

(❗️= breaking changes)

- [x] ❗️ Properly re-architecture the library to handle various source abstractions (#1275)
- [x] ❗️ Fix usage of `INestedOptions` to properly use the parent property's JSON name (#1276)
- [x] ❗️ Fix naming for `SourceTransactionCanceled` event type (#1282)
- [x] Handle `DateTime`s directly in the encoder (#1283)
- [x] ❗️ Remove `StripeDeleted` and add `Deleted` to relevant resources instead (#1284)
- [x] ❗️ Rename properties starting with a lower case letter (#1285)
- [x] ❗️ Rename all files and classes to remove the `Stripe` prefix (#1252)
- [x] ❗️ Fix services (#1286, #1287, #1288, #1291)
- [x] Use interfaces for common methods on services (#1269)
- [x] Make all value types in options classes nullable (#1298)
- [x] ❗️ Upgrade to API version 2018-09-24 (#1302)
- [x] ❗️ Convert all options class to reflect the API level structure, and rename `DateFilter` to `DateRangeOptions` (#1301)
- [x] ❗️ Rename `LiveMode` to `Livemode` (#1303)
- [x] Sanitize files (#1304, #1306)
- [x] Use `BasicService` for all services (#1305)
- [x] Sort service methods alphabetically (#1307)
- [x] Verify requests in tests (#1310)
- [x] ❗️ Better URL handling in services (#1308)
- [x] Group files by API resource like we started for sources for example: (#1309, #1312)
- [x] ❗️ Add missing properties on resources and removed incorrect ones along with a few fields being renamed to match the API (#1311)
- [x] ❗️ Add support for the `InvoiceItem` resource and keep `InvoiceLineItem` to describe a line item on an invoice (#1315)
- [x] Automatically deserialize Unix timestamps into `DateTime`s (#1316)
- [x] Create coverage report and upload to coveralls.io (#1318, #1319)
- [x] Revamp interfaces on Stripe model classes (#1317)
- [x] ❗️ Interfaces for polymorphic API resources (#1320, #1321, #1322 )
- [x] Fix warnings in .NET Framework specific code (#1323)
- [x] Add some missing tests (#1328)
- [x] ❗️ Use an interface for `PaymentIntentSourceAction` (#1329)
- [x] ❗️ Use `long`s instead of `int`s (#1331)
- [x] ❗️ Change the interface for `UsageRecord` methods to take a subscription item id (#1340)
- [x] ❗️ Renamed `SourceTokenOrExistingSourceId ` to `SourceId` (#1337)
- [x] Add support for `charge.expired` (#1345)

Fixes #1164 (via #1283).
Fixes #1260 (via #1269).
Fixes #1281 (via #1282).
Fixes #1330 (via #1331).
Fixes #1344 (via #1345).

We decided not to change how object expansion work for now. The current behaviour is more verbose but is clearer for the developers using the library so we will keep the approach of having 2 properties (a string ResourceId and the object Resource with the ResourceInternal that does the right handling).

### CODE REVIEW

**Comment by remi-stripe** [comment]
LGTM

**Comment by ob-stripe** [comment]
Okay, I've removed the WIP tag and rebased on master.

r? @remi-stripe for another set of 👀 before I pull this in

**Comment by ob-stripe** [comment]
Pulling this in 🎉

**Comment by ob-stripe** [comment]
Released as 20.0.0.

**Comment by buvinghausen** [comment]
Why was ISupportMetadata removed and nothing equivalent put in it's place?  I have extension methods that use that interface in order to return strongly typed values from the meta data and now I have to write each extension method for each object separately.  That's a giant pain in the ass I didn't need.

**Comment by ob-stripe** [comment]
@buvinghausen We removed it because it no longer served a purpose internally and we hadn't considered that it might be directly used by users. I don't see a problem with adding it back, though we'd rename it `IHasMetadata` to be consistent with the new `IHasId` and `IHasObject` interfaces.

**Comment by buvinghausen** [comment]
@ob-stripe I'm totally cool with an IHasMetadata replacement....

**Pull request merged**
