### PR TITLE
#1104: Added real parameterless constructors to all services

### LINKED ISSUE #1104: Suggestion: Services should have a real parameterless constructor
Having a real parameterless constructor allows classes to be used as generic types in methods with a `where T : new()` clause. A good example in the context of this library would be a service builder method that ensures only one instance of any given service is created:

```csharp
        private TService GetStripeService<TService>() where TService : StripeService, new()
        {
            var key = typeof(TService);

            if (!_services.TryGetValue(key, out var service))
            {
                lock(_services)
                {
                    if (!_services.TryGetValue(key, out service))
                    {
                        _services[key] = service = new TService();
                    }
                }
            }

            return service as TService;
        }
```

Since all Stripe .NET services have an optional `apiKey` parameter, replaced by `null` at compile-time, the above construction cannot be made. We have to remove the `new()` constraint and either use builders or reflection to create instances, which is less "elegant".

### PR DESCRIPTION
**Pull request by slimCODE**
This allows these services to serve as a generic type in methods with a `where TService : new()` clause.

Fixes #1104.

### CODE REVIEW

**Comment by brandur-stripe** [comment]
Thanks @slimCODE. This seems like it'll be useful and doesn't appear to be harmful in any way.

The one thing I noticed is that it seems like you've been relatively selective about which services get this treatment. Is there any reason for that? Your patch shows 20 files changed, but there are more like 36 services that are not one of the base classes:

```
$ ls -1 -R  src/Stripe.net/Services/ | grep 'Service.cs'
StripeBasicService.cs
StripeService.cs
Stripe3DSecureService.cs
StripeAccountService.cs
StripeApplePayDomainService.cs
StripeApplicationFeeRefundService.cs
StripeApplicationFeeService.cs
StripeBalanceService.cs
BankAccountService.cs
StripeCardService.cs
StripeChargeService.cs
CountrySpecService.cs
StripeCouponService.cs
StripeCustomerService.cs
StripeDiscountService.cs
StripeDisputeService.cs
StripeEphemeralKeyService.cs
StripeEventService.cs
StripeExchangeRateService.cs
StripeExternalAccountService.cs
StripeFileUploadService.cs
StripeInvoiceItemService.cs
StripeInvoiceService.cs
StripeLoginLinkService.cs
StripeOAuthTokenService.cs
StripeOrderService.cs
StripePayoutService.cs
StripePlanService.cs
StripeProductService.cs
StripeRefundService.cs
StripeSkuService.cs
StripeSourceTransactionService.cs
StripeSourceService.cs
StripeSubscriptionItemService.cs
StripeSubscriptionService.cs
StripeTokenService.cs
StripeTransferReversalService.cs
StripeTransferService.cs
```

(Also, you might want to add a "Fixes #1104" in your description above just so the issue gets linked somewhere.)

**Comment by slimCODE** [comment]
@brandur-stripe That was a louzy patch, I missed the ones deriving from `StripeBasicService<>`!

**Comment by brandur-stripe** [comment]
@slimCODE Ah I see what happened. Thanks for the quick fix!

Would you mind rebasing to get your two commits squashed down into one? That'll also give us a chance to try the CI build again, which seems to have hit an intermittent network problem and failed.

**Comment by slimCODE** [comment]
@ob-stripe I added those lines to normalize, as there were three lines everywhere else between the ctor (and props) and the "Sync" methods. If you prefer, I'll remove them.

**Comment by ob-stripe** [comment]
@slimCODE Ah no, that's fine then. Thanks for going the extra mile :)

**Comment by ob-stripe** [comment]
Released in 13.1.0. Thanks again for the contribution!

**Pull request merged**
