### PR TITLE
Remove the TotalCount property of lists

### PR DESCRIPTION
**Pull request by fred-stripe**
Fetching the total count of a list has already been removed from other Stripe libraries and is no longer recommended.

### CODE REVIEW

**Comment by brandur-stripe** [comment]
Mandatory comment that this is a breaking change, but other than that, I'm totally on board with seeing more references to this disappear.

**Comment by anelder-stripe** [comment]
I think I inadvertently broke your TotalCount removal by adding tests that depended on TotalCount.  🤕  Sorry!  Will fix.

**Comment by brandur-stripe** [comment]
@fred-stripe Mind rebasing this given that it's pretty stale (want to make sure the tests are still happy because I'm still not confident in my skills to fix them, hah)? I'm going to try and build up some release cadence here, so we'll get this in after you do. Thanks!

**Comment by ob-stripe** [comment]
I rebased the PR so that we can include it in the next major version bump.

**Pull request merged**
