### PR TITLE
follow secure coding BP, fix (#993)

### PR DESCRIPTION
**Pull request by bayotop**
I also fixed Xunit tests for events and added new facts for safe UTF8 behaviour.

### CODE REVIEW

**Comment by remi-stripe** [comment]
r? @brandur-stripe @fred-stripe 
Bumping this one to make sure it gets handled soon

**Comment by brandur-stripe** [comment]
Hi @bayotop, sorry about the long silence on this one!

Would you mind rebasing your branch and pushing? Unfortunately our test suite was broken for some time, but it's fixed now and I want to make sure that everything is passing as expected here. Thank you!

**Comment by bayotop** [comment]
I am not sure how to handle the failing tests that require an API key. I cloned a clean version of stripe:master and those tests are failing locally, too. 

Could you, please, provide any steps I should take to pass the appveyor check?

**Comment by ob-stripe** [comment]
Hey @bayotop, looks like something went wrong with your rebase -- there are now 68 commits in the PR, most of which are already merged in master.

In order to run the test suite locally, you need to provide a valid secret test API key in the `STRIPE_TEST_SK` environment variable. This should automatically happen when the test suite is run on AppVeyor, as it's part of the configuration in `appveyor.yml`.

**Comment by bayotop** [comment]
Damn, I am lost in git hell. I'll close the PR and create a fresh one. Sorry for any inconveniences.

**Pull request closed without merging**
