### PR TITLE
Add name to the Coupon resource

### PR DESCRIPTION
**Pull request by remi-stripe**
r? @ob-stripe 
cc @stripe/api-libraries

### CODE REVIEW

**Comment by ob-stripe** [comment]
Released in 16.11.0.

**Comment by winzig** [comment]
How does one update an existing coupon with the Name field? 

Is this Name field intended to be shown in the receipts/invoices instead of the coupon ID code? If so, it doesn't appear to be working at this time. At least in my test dashboard, the Name only shows up when creating the invoice. When I get the actual invoice/receipt email, it still shows the "ID code" for the coupon instead.

Thanks!

**Comment by remi-stripe** [comment]
@winzig This can not be updated today, it can only be set at creation. For the second part, it could be a bug but it's unrelated to the library. I would recommend contacting our support team to discuss this: https://support.stripe.com/email

**Comment by winzig** [comment]
@remi-stripe That's great news, I've filed a support request about the possible bug. 

In terms of the update capability, is this planned soon? I'm a bit squeamish about trying to create a new coupon and replacing the existing coupons on our existing subscriptions. Being able to just update the name param on existing coupons would be highly desirable.

**Comment by remi-stripe** [comment]
@winzig Not something we have planned for now but I will take this to the team and hopefully we can add this in the future

**Comment by remi-stripe** [comment]
@winzig  Issues are specific to bugs with the libraries so I would recommend against it. Since you reporting it to our support team (and I did too with the eng team) for now the only thing to do is wait for us to implement it. I will add it to the libraries once support for it is added in the API!

**Pull request merged**
